services:
  backend:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - database
    command: sleep infinity
    stop_grace_period: 2s

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: